openapi: "3.0.2"
info:
  title: "Gifts API"
  version: "1.0.0"
  description: "API for gifts"
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"

servers:
  - url: http://18.143.145.14/api/v1

paths:
  /register:
    post:
      security:
        - bearerAuth: []
      tags:
        - Authentication
      operationId: postUser
      summary: "Register a new user"
      requestBody:
        content:
          apliication/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required:
                    - name
                email:
                  type: string
                  required:
                    - email
                password:
                  required:
                    - password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationSuccess'
        '422':
          description: validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'The name field is required. (and 2 more errors)'
                  data:
                    type: object
                    example: null
        '500':
          description: 'Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /login:
    post:
      security:
        - bearerAuth: []
      tags:
        - Authentication
      operationId: userLogin
      summary: "Login user"
      description: "login and get token"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required:
                    - email
                password:
                  type: string
                  required:
                    - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationSuccess'
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                  error:
                    type: string
                    example: 'Email atau password salah'
                  data:
                    type: object
                    example: null
        '500':
          description: 'Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /gifts:
    get:
      security:
        - bearerAuth: []
      tags:
        - Gifts
      operationId: getAllGifts
      summary: "Get All Gifts"
      description: "Get all gifts"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Success'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Gift'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Unauthorized'
                  error:
                    type: string
                    example: 'Unauthorized'
                  data:
                    type: object
                    example: null
        '500':
          description: 'Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthenticationSuccess:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: "Berhasil login"
        error:
          type: string
          example: null
        data:
          type: object
          properties:
            token_type:
              type: string
              example: "Bearer"
            access_token:
              type: string
              example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL3YxL3JlZ2lzdGVyIiwiaWF0IjoxNjYzODExMzg3LCJleHAiOjE2NjM4MTQ5ODcsIm5iZiI6MTY2MzgxMTM4NywianRpIjoiZFY2eDBZaFlHSDdiazF2WiIsInN1YiI6Ijk2NWUxNTExLWFkZjEtNDA2MS1hYjI4LWI2OWNiZDc1ZGFlMyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.x8nnZVAN3YEzpCDmlBrRQLBZLFjHQBx_dn68jZTDueM"
            user:
              type: object
              properties:
                id:
                  type: string
                  example: "965e1511-adf1-4061-ab28-b69cbd75dae3"
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  example: "jhon@gmail.com"
                created_at:
                  type: string
                  example: "2021-06-24T09:16:27.000000Z"
                updated_at:
                  type: string
                  example: "2021-06-24T09:16:27.000000Z"
    AuthenticationFailed:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: string
          example: "Unauthorized"
        data:
          type: object
          example: null
    ServerError:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "Maaf, Terjadi kesalahan pada server"
        error:
          type: string
          example: "Maaf, Terjadi kesalahan pada server"
        data:
          example: null
    Gift:
      type: object
      properties:
        id:
          type: string
          example: 'efea95c8-2277-490d-a980-8e8f02bb5c10'
        name:
          type: string
          example: "Samsung Galaxy S21"
        price:
          type: string
          example: "10000"
        created_at:
          type: string
          example: "2021-06-24T09:16:27.000000Z"
        updated_at:
          type: string
          example: "2021-06-24T09:16:27.000000Z"
